# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-03 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clippings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
