# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clippings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='dropbox_thumb',
            field=models.URLField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='document',
            name='dropbox_path',
            field=models.URLField(blank=True, max_length=127),
        ),
    ]
