# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 09:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('clippings', '0002_auto_20170103_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.ManyToManyField(to='teams.TagObject', verbose_name='Содержит сведения о'),
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(2100)], verbose_name='Год'),
        ),
    ]
