# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clippings', '0003_auto_20170104_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='N/A', max_length=127, verbose_name='Название')),
                ('type', models.CharField(choices=[('photo', 'photo'), ('newspaper', 'newspaper'), ('magazine', 'magazine'), ('protocol', 'protocol'), ('program', 'program'), ('book', 'book')], default='photo', max_length=127, verbose_name='Тип')),
            ],
        ),
        migrations.CreateModel(
            name='SourceObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition', models.CharField(blank=True, max_length=127, verbose_name='Название')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='clippings.Source')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='clippings.SourceObject', verbose_name='Источник'),
        ),
    ]
