# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 10:36
from __future__ import unicode_literals

import clippings.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clippings', '0004_auto_20170104_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceobject',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='sourceobject',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)), verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='document',
            name='dropbox',
            field=models.FileField(blank=True, null=True, storage=clippings.models.MyDropbox(), upload_to='', verbose_name='Путь в Dropbox'),
        ),
        migrations.AlterField(
            model_name='document',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)), verbose_name='Год создания'),
        ),
    ]
