# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clippings', '0005_add-date-for-source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourceobject',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='clippings.Source'),
        ),
    ]
