# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-09 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clippings', '0009_auto_20170107_1229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('title', 'id')},
        ),
        migrations.AlterModelOptions(
            name='sourceobject',
            options={'ordering': ('source', 'year')},
        ),
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('photo', 'photo'), ('newspaper', 'newspaper'), ('magazine', 'magazine'), ('protocol', 'protocol'), ('program', 'program'), ('book', 'book'), ('other', 'other')], default='photo', max_length=127, verbose_name='Тип'),
        ),
    ]
