# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-28 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clippings', '0011_rename-clippings-fields-dummy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='source_main',
            new_name='source',
        ),
    ]
