# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clippings', '0013_auto_20170404_0742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='type',
            new_name='kind',
        ),
    ]
