# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 05:21
from __future__ import unicode_literals

from django.db import migrations
from django.db.models import Q


def update_type(apps, schema_editor):
    Document = apps.get_model("clippings", "Document")
    docs = Document.objects.filter(
        is_deleted=False
    ).filter(
        Q(kind='') | Q(kind__isnull=True)
    ).exclude(
        source__isnull=True
    )
    docs_dict = dict(docs.values_list('id', 'source__kind'))

    for document in docs:
        document.kind = docs_dict[document.id]
        document.save()


class Migration(migrations.Migration):

    dependencies = [
        ('clippings', '0014_auto_20170404_0821'),
    ]

    operations = [
        migrations.RunPython(update_type)
    ]
