# Generated by Django 2.2.17 on 2021-01-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clippings', '0015_auto_20170404_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='clippings.Source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='document',
            name='source_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to='clippings.SourceObject', verbose_name='Выпуск'),
        ),
    ]
