# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 09:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.City', verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='TagObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Базовое название')),
                ('story', models.TextField(verbose_name='История')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('tagobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teams.TagObject')),
                ('first_name', models.CharField(blank=True, max_length=127, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=127, verbose_name='Отчество')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)), verbose_name='Год рождения')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
            ],
            bases=('teams.tagobject',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('tagobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teams.TagObject')),
                ('short_name', models.CharField(blank=True, max_length=32, verbose_name='Короткое название')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)), verbose_name='Год создания')),
                ('disband_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)), verbose_name='Год распада')),
                ('year_prefix', models.CharField(blank=True, max_length=64, null=True, verbose_name='Префикс к году образования')),
                ('disband_year_prefix', models.CharField(blank=True, max_length=64, null=True, verbose_name='Префикс к году распада')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.City', verbose_name='Город')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.Team', verbose_name='Команда-родитель')),
            ],
            bases=('teams.tagobject',),
        ),
    ]
