# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 08:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_city_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='team',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ancestors', to='teams.Team', verbose_name='Команда-родитель'),
        ),
    ]
