# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-13 05:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_personseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='personseason',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_person_seasons', to='teams.Team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='personseason',
            name='year',
            field=models.PositiveSmallIntegerField(validators=(django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)), verbose_name='Год'),
        ),
    ]
