# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-14 05:38
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_add_team_to_personseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dod',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AddField(
            model_name='person',
            name='year_death',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)), verbose_name='Год смерти'),
        ),
    ]
