# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-14 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0008_add_death_to_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_dead',
            field=models.BooleanField(default=False, verbose_name='Умер'),
        ),
    ]
