# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-17 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20170104_1313'),
        ('teams', '0009_add_bool_isdead_to_person'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personseason',
            options={'ordering': ('-year',)},
        ),
        migrations.AddField(
            model_name='personseason',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_person_seasons', to='matches.Tournament', verbose_name='Турнир'),
        ),
    ]
