# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-23 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_add_level_to_Tournament'),
        ('teams', '0010_add_tournament_to_person_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personseason',
            name='role',
            field=models.CharField(choices=[('player', 'игрок'), ('prop', '1/3'), ('hooker', '2'), ('lock', '4/5'), ('backrow', '6-8'), ('scrum-half', '9'), ('fly-half', '10'), ('center', '12/13'), ('winger', '11/14'), ('fullback', '15'), ('referee', 'судья'), ('coach', 'тренер')], default='player', max_length=127, verbose_name='Амплуа'),
        ),
        migrations.AlterUniqueTogether(
            name='personseason',
            unique_together=set([('person', 'year', 'tournament', 'role')]),
        ),
    ]
