# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-23 18:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_add_level_to_Tournament'),
        ('teams', '0011_unique_together_personseason'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=127, verbose_name='Базовое название')),
                ('year', models.PositiveSmallIntegerField(validators=(django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)), verbose_name='Год')),
                ('story', models.TextField(blank=True, verbose_name='История')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_team_seasons', to='matches.Season', verbose_name='Турнир')),
            ],
            options={
                'ordering': ('-year', 'team'),
            },
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('year',)},
        ),
        migrations.AlterField(
            model_name='tagobject',
            name='story',
            field=markdownx.models.MarkdownxField(blank=True, verbose_name='История'),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='teams.Team', verbose_name='Команда'),
        ),
        migrations.AlterUniqueTogether(
            name='teamseason',
            unique_together=set([('team', 'year', 'season')]),
        ),
    ]
