# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 06:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_add_teamseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='draws',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=django.core.validators.MaxValueValidator(100), verbose_name='Н'),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='losses',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=django.core.validators.MaxValueValidator(100), verbose_name='П'),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='played',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=django.core.validators.MaxValueValidator(100), verbose_name='И'),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=django.core.validators.MaxValueValidator(100), verbose_name='О'),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='score',
            field=models.CharField(blank=True, max_length=10, verbose_name='Р/О'),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='wins',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=django.core.validators.MaxValueValidator(100), verbose_name='В'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)), verbose_name='Год'),
        ),
    ]
