# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_remove_tournament_from_personseason'),
        ('teams', '0014_personseason_fk_to_season'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personseason',
            options={'ordering': ('-year', 'season', 'role')},
        ),
        migrations.AlterField(
            model_name='personseason',
            name='role',
            field=models.CharField(choices=[('20-player', 'игрок'), ('01-prop', '1/3'), ('02-hooker', '2'), ('03-lock', '4/5'), ('04-backrow', '6-8'), ('05-scrum-half', '9'), ('06-fly-half', '10'), ('07-center', '12/13'), ('08-winger', '11/14'), ('09-fullback', '15'), ('30-referee', 'судья'), ('40-coach', 'тренер')], default='20-player', max_length=127, verbose_name='Амплуа'),
        ),
        migrations.AlterField(
            model_name='personseason',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_person_seasons', to='matches.Season', verbose_name='Розыгрыш турнира'),
        ),
        migrations.AlterField(
            model_name='personseason',
            name='story',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.RemoveField(
            model_name='personseason',
            name='tournament',
        ),
        migrations.AlterUniqueTogether(
            name='personseason',
            unique_together=set([('person', 'year', 'season', 'role')]),
        ),
    ]
