# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-08 05:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0015_remove_tournament_from_personseason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='year',
            new_name='year_birth',
        ),
    ]
