# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-14 05:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0016_person_year_birth_rename'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MaxValueValidator(40),), verbose_name='Сортировка'),
        ),
        migrations.AddField(
            model_name='teamseason',
            name='place',
            field=models.CharField(blank=True, max_length=2, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='draws',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MaxValueValidator(100),), verbose_name='Н'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='losses',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MaxValueValidator(100),), verbose_name='П'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='played',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MaxValueValidator(100),), verbose_name='И'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MaxValueValidator(100),), verbose_name='О'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='matches.Season', verbose_name='Турнир'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='wins',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=(django.core.validators.MaxValueValidator(100),), verbose_name='В'),
        ),
    ]
