# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-25 04:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_add_place_teamseason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamseason',
            options={'ordering': ('-year', 'team', 'order')},
        ),
    ]
