# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0018_add_group_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personseason',
            name='role',
            field=models.CharField(choices=[('20-player', 'игрок'), ('01-prop', '1, 3'), ('02-hooker', '2'), ('04-lock', '4/5'), ('06-backrow', '6-8'), ('09-scrum-half', '9'), ('10-fly-half', '10'), ('12-center', '12/13'), ('14-winger', '11/14'), ('15-fullback', '15'), ('03-firstrow', '1-3'), ('08-forward', '1-8'), ('10-half', '9-10'), ('15-back', '11-15'), ('30-referee', 'судья'), ('40-coach', 'тренер')], default='20-player', max_length=127, verbose_name='Амплуа'),
        ),
    ]
