# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_tagthrough'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Базовое название')),
                ('from_day', models.DateField(verbose_name='Дата начала')),
                ('to_day', models.DateField(verbose_name='Дата окончания')),
                ('is_known', models.BooleanField(default=True, verbose_name='Подтверждено')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='teams.Team', verbose_name='Команда')),
            ],
        ),
    ]
