# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0021_teamname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamname',
            options={'ordering': ('team', 'from_day')},
        ),
        migrations.AlterField(
            model_name='teamname',
            name='to_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
