# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-06 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0024_team_team_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupseason',
            options={'ordering': ('order', '-year', 'team')},
        ),
    ]
