# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-31 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0025_auto_20200106_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Число участников'),
        ),
    ]
