# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-31 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0026_add_TeamSeason_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamseason',
            name='participants',
        ),
    ]
