# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-31 08:01
from __future__ import unicode_literals

from django.db import migrations, models


def forwards(apps, schema_editor):
    TeamSeason = apps.get_model("teams", "TeamSeason")
    for ts in TeamSeason.objects.select_related('season'):
        if not ts.season.participants:
            ts.has_position = False
            ts.save()


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0027_remove_participants_from_TeamSeason'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='has_position',
            field=models.BooleanField(default=True, verbose_name='Есть позиция в таблице'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
