# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-31 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0028_add_has_position_to_TeamSeason'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='display_name',
            field=models.CharField(blank=True, max_length=127, null=True, verbose_name='Полное наименование сезона'),
        ),
    ]
