# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-31 08:32
from __future__ import unicode_literals

import datetime as dt
from django.db import migrations


def get_name_for(team, year):
    """Return name which team born in a given year."""
    default = team.short_name
    from_db = team.names.reverse().filter(
        from_day__lte=dt.date(year, 1, 1)
    ).values_list('name', flat=True).first()
    return from_db or default


def forwards(apps, schema_editor):
    TeamSeason = apps.get_model("teams", "TeamSeason")
    for self in TeamSeason.objects.select_related('season', 'team'):
        team = get_name_for(self.team, self.year)
        self.name = team
        self.display_name = f"{team}: {self.season.name}"
        self.save()
    ts_without_display = TeamSeason.objects.filter(display_name__isnull=True)
    print("\nTeamSeason without diaply_name", ts_without_display.count())


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0029_add_display_name_to_TeamSeason'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
