# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-31 08:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0030_populate_display_name_for_TeamSeason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='year_birth',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)], verbose_name='Год рождения'),
        ),
    ]
