# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-31 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0031_allow_birth_up_to_1800_for_Person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseason',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=127, verbose_name='Полное наименование сезона'),
            preserve_default=False,
        ),
    ]
