# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-06 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0032_make_display_name_in_TeamSeason_mandatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamseason',
            name='show_group',
            field=models.BooleanField(default=False, verbose_name='Есть позиция в таблице'),
        ),
    ]
