# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-06-06 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0033_make_flag_for_show_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamseason',
            name='show_group',
            field=models.BooleanField(default=False, verbose_name='Брать название из группы'),
        ),
    ]
