# Generated by Django 2.2.17 on 2021-01-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0034_auto_20200606_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personseason',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_person_seasons', to='matches.Season', verbose_name='Розыгрыш турнира'),
        ),
        migrations.AlterField(
            model_name='personseason',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='_person_seasons', to='teams.Team', verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='team',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ancestors', to='teams.Team', verbose_name='Команда-родитель'),
        ),
        migrations.DeleteModel(
            name='TagThrough',
        ),
    ]
