# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('tagobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teams.TagObject')),
                ('home_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Счёт хозяев')),
                ('away_score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Счёт гостей')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата матча')),
                ('away', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.Team', verbose_name='Гости')),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.Team', verbose_name='Хозяева')),
                ('ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_reffed', to='teams.Person', verbose_name='Судья')),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='teams.Stadium', verbose_name='Стадион')),
            ],
            bases=('teams.tagobject',),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('tagobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teams.TagObject')),
            ],
            bases=('teams.tagobject',),
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('tagobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teams.TagObject')),
            ],
            bases=('teams.tagobject',),
        ),
        migrations.AddField(
            model_name='season',
            name='tourn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='matches.Tournament', verbose_name='Турнир'),
        ),
        migrations.AddField(
            model_name='match',
            name='tourn_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.Season', verbose_name='Турнир'),
        ),
    ]
