# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 10:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='date_end',
            field=models.DateField(default=datetime.date(1936, 1, 1), verbose_name='Дата окончания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='date_start',
            field=models.DateField(default=datetime.date(1936, 1, 1), verbose_name='Дата начала'),
            preserve_default=False,
        ),
    ]
