# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_add_level_to_Tournament'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('date_end__year', 'tourn')},
        ),
    ]
