# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-27 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_remove_tournament_from_personseason'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ('tourn', 'date_start')},
        ),
    ]
