# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0020_tagthrough'),
        ('matches', '0009_auto_20171028_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='teams.City', verbose_name='Город'),
        ),
    ]
