# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-25 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0011_group_round_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='round_type',
            field=models.CharField(choices=[('round-robin', 'round-robin'), ('knockout', 'knockout'), ('misc', 'misc')], default='round-robin', max_length=127, verbose_name='Тип игр'),
        ),
    ]
