# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-08 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0014_match_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='display_name',
            field=models.CharField(max_length=255, verbose_name='Отображение'),
        ),
    ]
