# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-30 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0016_auto_20200106_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tech_away_loss',
            field=models.BooleanField(default=False, verbose_name='Поражение хозяевам'),
        ),
        migrations.AddField(
            model_name='match',
            name='tech_home_loss',
            field=models.BooleanField(default=False, verbose_name='Поражение гостям'),
        ),
        migrations.AddField(
            model_name='match',
            name='technical',
            field=models.BooleanField(default=False, verbose_name='Технический результат'),
        ),
    ]
