# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-31 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0017_add_technical_to_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tech_away_loss',
            field=models.BooleanField(default=False, verbose_name='Поражение гостям'),
        ),
        migrations.AlterField(
            model_name='match',
            name='tech_home_loss',
            field=models.BooleanField(default=False, verbose_name='Поражение хозяевам'),
        ),
    ]
