# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-05-31 07:10
from __future__ import unicode_literals

from django.db import migrations, models


def forwards(apps, schema_editor):
    TeamSeason = apps.get_model("teams", "TeamSeason")
    for ts in TeamSeason.objects.exclude(participants__isnull=True):
        ts.season.participants = ts.participants
        ts.season.save()


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0018_add_TeamSeason_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='participants',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Число участников'),
        ),
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
