# Generated by Django 2.2.17 on 2021-01-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0019_move_participants_to_Season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='tourn_season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='matches.Season', verbose_name='Турнир'),
        ),
    ]
